.

diff --git a/.github/workflows/on-push-ci.yml b/.github/workflows/on-push-ci.yml
--- a/.github/workflows/on-push-ci.yml
+++ b/.github/workflows/on-push-ci.yml
@@ -83,7 +83,7 @@ jobs:
             echo "Error: TRX file not found: $xml_file"
             exit 1
          fi
-         specific_element=$(xmlstarlet sel -t -v "//UnitTestResult[last()]/Output/StdOut" "$xml_file" 2>/dev/null || echo "Error: XPath expression not found")
+         specific_element=$(xmlstarlet sel -t -v "//ns:UnitTestResult[last()]/ns:Output/ns:StdOut" "$xml_file" 2>/dev/null || echo "Error: XPath expression not found")
          if [ "$specific_element" = "Error: XPath expression not found" ]; then
             echo "Error: XPath expression not found in the XML file."
             exit 1
