a

diff --git a/.github/workflows/on-push-ci.yml b/.github/workflows/on-push-ci.yml
--- a/.github/workflows/on-push-ci.yml
+++ b/.github/workflows/on-push-ci.yml
@@ -81,9 +81,15 @@ jobs:
 
       - name: Get Test Results
         run: |
-            /usr/bin/xmlstarlet sel -t -v "(//UnitTestResult[last()]/Output/StdOut)" /home/runner/work/AssessmentSystem/AssessmentSystem/Assesment.Tests/TestResults/test-results.trx
-            # echo "$last_stdout"
-            # echo "::set-output name=last-stdout::$last_stdout"
+            last_stdout=$(/usr/bin/xmlstarlet sel -t -v "(//UnitTestResult[last()]/Output/StdOut)" /home/runner/work/AssessmentSystem/AssessmentSystem/Assesment.Tests/TestResults/test-results.trx)
+            exit_code=$?
+            if [ $exit_code -ne 0 ]; then
+              echo "Error occurred while running xmlstarlet. Exit code: $exit_code"
+              echo "::error::Error occurred while running xmlstarlet. Exit code: $exit_code"
+            else
+              echo "$last_stdout"
+              echo "::set-output name=last-stdout::$last_stdout"
+            fi
 
           # passed=$(echo "$total_points" | grep -oP 'Passed\s*:\s*\K\d+')
           # failed=$(echo "$total_points" | grep -oP 'Fail\s*:\s*\K\d+')
