.

diff --git a/.github/workflows/on-push-ci.yml b/.github/workflows/on-push-ci.yml
--- a/.github/workflows/on-push-ci.yml
+++ b/.github/workflows/on-push-ci.yml
@@ -77,10 +77,38 @@ jobs:
 
       - name: Get Element
         run: |
-         xml_file="${{ env.TRX_FILE_PATH }}"
-         cat "${{ env.TRX_FILE_PATH }}"
-         xmlstarlet sel -N ns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010" -t -v "//ns:UnitTestResult[last()]/ns:Output/ns:StdOut" "$xml_file" > result.txt
-         echo "SPECIFIC_ELEMENT=result.txt" >> $GITHUB_ENV
+         # Set the XML file path
+            xml_file="${{ env.TRX_FILE_PATH }}"
+
+            # Check if the file exists
+            if [ ! -f "$xml_file" ]; then
+              echo "Error: TRX file not found: $xml_file"
+              exit 1
+            fi
+
+            # Print the content of the TRX file (optional)
+            cat "$xml_file"
+
+            # Extract the desired element using xmlstarlet
+            output=$(xmlstarlet sel -N ns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010" -t -v "//ns:UnitTestResult[last()]/ns:Output/ns:StdOut" "$xml_file")
+
+            # Check if xmlstarlet command was successful
+            if [ $? -ne 0 ]; then
+              echo "Error: Failed to extract element from XML using xmlstarlet"
+              exit 1
+            fi
+
+            # Write the extracted output to result.txt
+            echo "$output" > result.txt
+
+            # Check if writing to result.txt was successful
+            if [ $? -ne 0 ]; then
+              echo "Error: Failed to write extracted element to result.txt"
+              exit 1
+            fi
+
+            # Set the environment variable with the path to result.txt
+            echo "SPECIFIC_ELEMENT=result.txt" >> $GITHUB_ENV
 
       - name: Print XML content
         run: |
