refactor: github workflow continue running even when unit tests fail

diff --git a/.github/workflows/on-push-ci.yml b/.github/workflows/on-push-ci.yml
--- a/.github/workflows/on-push-ci.yml
+++ b/.github/workflows/on-push-ci.yml
@@ -49,8 +49,8 @@ jobs:
           GITHUB_TOKEN: ${{ github.token }}
 
       - name: Test
-        # run: dotnet test ${{ vars.SOLUTION_PATH }} --logger "trx;LogFileName=test-results.trx" || true  *With this CI continue to run whether tests fail or not
-        run: dotnet test ${{ vars.SOLUTION_PATH }} --logger "trx;LogFileName=test-results.trx"
+        run: dotnet test ${{ vars.SOLUTION_PATH }} --logger "trx;LogFileName=test-results.trx" || true  *With this CI continue to run whether tests fail or not
+        # run: dotnet test ${{ vars.SOLUTION_PATH }} --logger "trx;LogFileName=test-results.trx"
       - name: Test Report
         uses: dorny/test-reporter@v1
         if: always()
