.

diff --git a/.github/workflows/on-push-ci.yml b/.github/workflows/on-push-ci.yml
--- a/.github/workflows/on-push-ci.yml
+++ b/.github/workflows/on-push-ci.yml
@@ -22,8 +22,9 @@ jobs:
       - name: Check branch name
         run: |
           if [[ "${GITHUB_REF}" != "refs/heads/exam/${{ github.event.pull_request.head.ref }}" ]]; then
-            echo "Branch name does not match the required pattern."
-            exit 1
+                echo "The branch '${GITHUB_REF}' does not match the required pattern."
+                echo "The source branch of the pull request '${{ github.event.pull_request.head.ref }}' should be prefixed with 'exam/'."
+                exit 1
           fi
       - uses: actions/checkout@v3
       - name: Checkout Code
