Final changes

diff --git a/.github/workflows/on-push-ci.yml b/.github/workflows/on-push-ci.yml
--- a/.github/workflows/on-push-ci.yml
+++ b/.github/workflows/on-push-ci.yml
@@ -1,10 +1,9 @@
-name: CI/CD On Push Workflow
+name: Exam Pipeline
 
 on:
   push:
-    branches: [ "main" ]
-  # pull_request:
-  #   branches: [ "main"]
+    branches:
+      - 'exam/*'
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -20,6 +19,12 @@ jobs:
       ACTIONS_STEP_DEBUG: true
 
     steps:
+      - name: Check branch name
+        run: |
+          if [[ "${GITHUB_REF}" != "refs/heads/exam/${{ github.event.pull_request.head.ref }}" ]]; then
+            echo "Branch name does not match the required pattern."
+            exit 1
+          fi
       - uses: actions/checkout@v3
       - name: Checkout Code
         uses: actions/setup-dotnet@v3
